dist: trusty
jdk: oraclejdk8
language: java
services:
  - postgresql
  - docker
env:
  global:
#    - secure: "oso6mOuG4b4bjwYVDLgtsOpgdEnMtvnerakAagke9alOBVupIVmh1CUOfdeDU822v8N2mh4isvU16vLR8zV5Gu2m45Z3QDrDwqZh6qu6sDiGSt2Ybtg6zhfM5FmIX+/FBKePxnVeIKfISg5fBkam5hjPjlevYPeK9Yo3ZTJlkTFmh9Q5zE3zjLA+jtUJGYOZFBWBZho158szUj7yO2H5h0NEfvTJpKiQJWbMSqXuc7ZITwP7mSIavIqxCwB3550GE0mPZlITmgYgj5yAlQwiCZsc1xo4mHj/en1yo3nAPK30QD/sm+Ii4tKGP3roFDEVVIVj5TYt9XpgyqhQ/Vf6EZDMFDELahl43TpAOqqpeF7H5kgFrRrRSKykTw6YU5yPn2jf5S7vtbwEZ/c1l/Z4o9pTrpZaWvWJ6pRxA9rL9B2oqkqVNuHO5xqb+e5l0187SaU6hnV0jrJu4LSKhhOOwI1krpQwkr3ORfdkbUfGFaZIyezp5OPPptn/yklVUaF8vhaVRW919q0wd6fzF8+wMgIJGCrY29IEpwvr9g4bvHRGMqZYng6oLkw9R+uAq0ZiuvJ8J9qNIMgZQaza6ugkssTPKERo/54DjPlI7f5Pwvnx/4pLYNSbcyFyNYEQR3h47WFNdTvriyEEIaR95PgE22Yq1BoBI+0wrLAp/t72S9M="
    - secure: "tIi6q4BFFX/ReMP8xawYcvaWfCGJyIY8kR8S+nOd0WcbPmP1p3AaDO+wtTPs97GvMPThz0r5uviAu8MT0K2bLJqo5YGvlCn3rtDV8hDjJtsnSquL8qj+R85Xqlb60Jct3Qbpq5KPooH6t7+TZKEROCxam9jdXI7ZGE/4JtOzHPQGA0EWiwMHZLMapYb5BIQUh7sUPLVOIQGIyXQlI0cG6FE4Jnrve+1wmQVodVVBuVGCGNC7NgjUHQReYAm1DQJgDOD4AOOBwFNEeXveUbMR36yyCFH+qzFV20qx2Z/SjJdJ6dlzjfqgnYs3shEn2L7IQyO3jVjan7evmeydOum7o5JvyKS12PFvFp0uOpAUeuWFpnqcnwXGdKkqjvY/TZsk/8GRHbB76VVo+9Loeo/uepAgaUaZFP0rI9rH3DpISYYHbHIEVVTh4QwDbK8F56vKluta+dICwrV+G6e/pkK2KK0OFq78e3tW+zqrIIK1jzsQcNWpN/LCztbUxAAX8X65QGcX2gOkOgFr5SfQFzd2BhfqvgzWFNdZZgFSPdg3H1FtYS6qB69IhXE0kJusAx06WiANeeCUJIJERj3tqjAeYXdvtPaPexTwSGB6tRzu+BWPdd2spjjufwXW3K6G6OFGKLxp3s1DPBiK+/7EeDUyLa+E/Vn3UqDX//1D/NxoHG4="
    - secure: "iCIUaVWtQzbazYalA2h0oyg68qMS+hXDfmdmw6b6z/xD3xUeGiumur+E6u/7yi76F6PHtYpfYXAAeK/XPodXxQqQEj0tgEkZIkl5wN6CR5A/thJ+jS4GbWBwyowLb2K/4zx7sgQDmf1EH+UTT4BEYvjJwtnjS1A1u4/S5qtJ93+aScWw629DyjqYQZdeu8yC9VH6YE5dWb9NjxXu4rEBDdrjhTIjZMbLLDxMhJZriZgS+uAOLIyeZ2Cnk72m3jNkGX2WAriiMQK5nrMBLYAzX7eIdvhL+aHIrqJ7V0uJMIdLwaqPliUQt67QXkydUweRAJ/CPBd4lxHF6dQTwMjbwD7P9Fod6lTn5gNWnT0j7OBJuwqRaS7seza392Y8ZWqigxFNItCeahUYbJEDIs8k/J3BVX6E7j8voVO7z40i4GYZE90mw/86SaKlcR9WvXbncTxYlvsngYH6rMPvd1eetFjBQbYqRMmQiPN/buyQ78ljPzoxaef8EWJYW0dn62hkbua7j8GvQIGZQHmkvTn+sttIdj5joHpic54PRwSw1VLIL1hc9qNwKvyI7BlOEXG7oG/eiTPe8fsYKXRKAJrGtCZC4IlQvcEIDczjMvNKuvqfdLEymgUlNbn9xor/BNw01ssWAy2FvWw6buYkJuWk1Ij8cqS59xMsja55zvWojHw="
    - secure: "ZTDovBkt1JFhx2BdW5gBlo8QoM8aMscVskoNtKRLjMr6hL1fSCgUfIYKjWROuHccarOnhKm2XRIjWqpX/KjYeWnh7w10VRFDIn8f8aCsT3ULiumMR3TgkSn5IzGnjK8DoaXFhLJB2om1kEd9bDqqA5598JYRSQSEUF52lnkORFCingrHG6Y/7+TlMPZ8i7DE/G/8omwvVuHA5eVpvElr79+PBQQMnlC2musfrqIgA/T6QLYJ40vCG7xzWAUQu+5/S9wmeiTHEHHb3zA0Qao/d9+3SZVTi5Lg2pdx2RHU8FMgzeYBFRbL+UiH1uceOUXul/rFrVcbYDsPlHolc4at3k7Giffh+ooopuTBkaljkXvFitdkRMeW9e4q/doHB95pyO4uSHBbzplsES+A1YnX7q272kPOTcLEmGU4ey3m+vp0CBeMRiNs9SHQapT5kWAhOHFLXFkuV83hjH/u7evBQLYxt234qIiltHQMSYK2aIK4+OCz5jaqR0BatYd3R7x2vR9sV2s9V8lxqZ290S7mXQ6m6rUGmxHZSW6mG5WPRn6aZK+tbaHt5GGkfumGMQ3fUUFgUUP6cGwDD7hG48yliw/guEf1hSKtEDCz9R4NfMen97K3yYxSwVsmEW0QAMO+HhJPE56pPFCDTKysS+CDClTpTQSnhow9LXRCz2MLkzQ="
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$TRAVIS_BRANCH"; fi`
  - export IMAGE_NAME=myapi/main-repo
  - docker build -t $IMAGE_NAME:latest .
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:$TAG

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mirabila
